# 第9回勉強会
## 科学におけるPy
## 1. 標準ライブラリでの数学と統計
### math関数

In [4]:
# math関数
import math # 標準ライブラリの数学関数
math.pi　# 定数

3.141592653589793

In [3]:
math.e # 定数

2.718281828459045

In [6]:
math.fabs(-271.1) # 引数の絶対値

271.1

In [9]:
math.floor(-271.1) # 引数以下で最も大きい整数

-272

In [8]:
math.ceil(-271.1) # 引数以上で最も小きい整数

-271

In [11]:
math.factorial(10) # 10の階乗

3628800

In [45]:
math.log(1.0) # eを底とする引数の対数を計算

0.0

In [13]:
math.log(math.e)# eを底とする引数の対数を計算

1.0

In [15]:
math.log(8, 2) # 別の底を使いたい場合、それを第2引数として指定する

3.0

In [17]:
math.pow(2, 3) # 逆に、第1引数の第2引数乗を計算する

8.0

In [19]:
# （組み込みの指数演算子の場合）
# 基数と指数がともに整数なら、結果をfloatに自動変換しない
2**3

8

In [25]:
math.sqrt(100.0) # 100の平方根

10.0

In [26]:
x = 3.0
y = 4.0
math.hypot(x,y)

5.0

In [27]:
math.radians(180.0) # 度数法→弧度法

3.141592653589793

In [28]:
math.degrees(math.pi) # 弧度法→度数法

180.0

### 複素数の操作

In [33]:
# 実数
5

5

In [34]:
# 虚数
8j

8j

In [35]:
# 虚数
3 + 2j

(3+2j)

In [38]:
# 虚数i（Pythonの1j）は、-1の平方根と定義されている
1j*1j

(-1+0j)

In [39]:
(7 + 1j) * 1j

(-1+7j)

### decimalによる正確な浮動小数点数計算

In [43]:
x = 10.0/3.0 # 2のべき乗で表現できない数値は、正確に表現できないことが多い
x 

3.3333333333333335

In [47]:
# ドルとセントを浮動小数点でまとめて表現する
# 指定した有効桁数で数値を表現する必要がある 
from decimal import Decimal
price = Decimal('19.99')
tax = Decimal('0.06')
total = price + (price * tax)
total

Decimal('21.1894')

In [48]:
# 最も近いセントを求める
penny = Decimal('0.01')
total.quantize(penny)

Decimal('21.19')

### fractionsによる有理数計算 

In [49]:
from fractions import Fraction # 1/2に2/3を掛ける計算
Fraction(1, 3) * Fraction(2, 3)

Fraction(2, 9)

In [53]:
# Fractionの中でDecimalを使うことが出来る
Fraction(1.0/3.0)

Fraction(6004799503160661, 18014398509481984)

In [55]:
Fraction(Decimal('1.0')/Decimal('3.0'))

Fraction(3333333333333333333333333333, 10000000000000000000000000000)

In [72]:
# gcd関数で二つの数の最大公約数を求める
import math
math.gcd(24, 16)

8

### arrayによるパッキングされたシーケンス

### atatisticsによる単純な統計

### 行列の乗算

## 2. Scientific Python

## 3. NumPy

### array()による配列の作成

In [4]:
# NumPyとは、Pythonにおいて数値計算を効率的に行うための拡張モジュール
# 型付きの多次元配列（例えばベクトルや行列などを表現できる）のサポートをPythonに加える
# それらを操作するための大規模な高水準の数学関数ライブラリを提供する
import numpy as np
b = np.array([2,4,6,8])
b

array([2, 4, 6, 8])

In [66]:
# ndim属性は、階数(rank,次元数のこと)を返す
b.ndim

1

In [67]:
# sizeによって配列内の値の総数が得られる
b.size

4

In [68]:
# shapeによって各階の値の数が得られる
b.shape

(4,)

### arange()による配列の作成

In [69]:
a = np.arange(10) # Python標準のrange()と似ている
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a.ndim

1

In [74]:
a.shape

(10,)

In [75]:
a.size

10

In [77]:
# 二つの値を渡すと、最初の値から第2の値マイナス1までの配列が作られる
a = np.arange(7, 11)
a

array([ 7,  8,  9, 10])

In [79]:
# 第3引数として1以外のステップ数を指定できる
a = np.arange(7,11,2)
a

array([7, 9])

In [80]:
# floatでもきちんと動作する
f = np.arange(2.0, 9.8, 0.3)
f

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3, 5.6,
       5.9, 6.2, 6.5, 6.8, 7.1, 7.4, 7.7, 8. , 8.3, 8.6, 8.9, 9.2, 9.5,
       9.8])

In [81]:
# dtype引数を指定すると、どの型の値を生成するかをarangeに指示できる
g = np.arange(10, 4, -1.5, dtype=np.float)
g

array([10. ,  8.5,  7. ,  5.5])

### zeros()、ones()、random()による配列の作成

In [3]:
# zeros()メソッドは、全ての値がゼロになっている配列を返す
# 引数として配列の形を指定するタプルを渡せる
# 1次元配列の例
a = np.zeros((3,))
a

array([0., 0., 0.])

In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [7]:
a.size

3

In [8]:
# 次の列は、回数が2になっている
b = np.zeros((2, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 4)

In [11]:
b.size

8

In [15]:
# zeros()と同様、同じ値で配列を初期化する特殊関数
# ones()はすべての値が1になっている配列を返す
# random()はすべての値が0.0から1.0までの無作為な値になっている配列を返す
k = np.ones((3, 5))
k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
m = np.random.random((3, 5))
m

array([[0.20070755, 0.15983706, 0.59674603, 0.36648916, 0.8173344 ],
       [0.24516816, 0.900154  , 0.3791595 , 0.63217793, 0.97989518],
       [0.61562108, 0.93550767, 0.33295525, 0.28607732, 0.87916419]])

In [16]:
# リストやタプルと配列は似ている
# 違いの一つは、reshape()を使った配列形状の変更
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = a.reshape(2,5)
a 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
a.ndim

2

In [19]:
a.shape

(2, 5)

In [20]:
a.size

10

In [23]:
a = a.reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
a.shape = (2, 5)
a # shapenに形状を指定するタプルを代入する方法でもよい

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
a = a.rehape(3,4)
a # 各階のサイズの積が、値の総数と同じでなければならない

AttributeError: 'numpy.ndarray' object has no attribute 'rehape'

### []による要素の取得

In [26]:
# 1次元配列は、リストと同じように動作する
a = np.arange(10)
a[7]

7

In [28]:
a[-1]

9

In [29]:
a.shape = (2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
# 配列の形状が異なる場合には、カンマ区切りの添字を使う
a[1,2]

7

In [1]:
# Pythonの2次元リストとは異なる
i = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
i

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [7]:
i[1, 2]

TypeError: list indices must be integers or slices, not tuple

In [8]:
i[1][2]

7

In [45]:
# スライスは、1セットしかない角かっこの中で使わなければならない
a = np.arange(10)
a = a.reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
a[0, 2:]

array([2, 3, 4])

In [47]:
a[-1, :3]

array([5, 6, 7])

In [48]:
# スライスを使って複数の要素に値をまとめて代入することもできる。
# 全ての行のオフセット2と3の列に1000を代入する
a[:, 2:4] = 1000
a

array([[   0,    1, 1000, 1000,    4],
       [   5,    6, 1000, 1000,    9]])

### 配列の数学演算

In [49]:
# NumPyの再定義された乗算（*）演算子を使って、NumPy配列のすべての要素に同じ値をかける
from numpy import *
a = arange(4)
a

array([0, 1, 2, 3])

In [50]:
a *= 3
a

array([0, 3, 6, 9])

In [51]:
# Python標準リストの各要素に同じ値をかける
# ループかリスト内包表記を使わなければならない
plain_list = list(range(4))
plain_list

[0, 1, 2, 3]

In [52]:
plain_list = [num * 3 for num in plain_list]
plain_list

[0, 3, 6, 9]

In [53]:
# 一斉演算の動作は、NumPyライブラリの他の関数にも当てはまる
# zeros()と＋を使って、すべての要素を同じ値で初期化する
from numpy import *
a = zeros((2,5)) + 17.0
a

array([[17., 17., 17., 17., 17.],
       [17., 17., 17., 17., 17.]])

### 線形代数

In [54]:
# (例)連立1次方程式
# 4x + 5y = 20
#  x + 2y = 13

In [11]:
# 係数（xとyにかけられている値）と従属変数（方程式の右辺）の配列を作る
import numpy as np
coefficients = np.array([[4, 5], [1, 2]])
dependents = np.array( [20, 13] )
answers = np.linalg.solve(coefficients, dependents)
answers

array([-8.33333333, 10.66666667])

In [12]:
4 * answers[0] + 5 * answers[1]

20.0

In [13]:
1 * answers[0] + 2 * answers[1]

13.0

In [14]:
# NumPyに配列のドット積を計算させれば、大量の入力を避けられる

In [15]:
product = np.dot(coefficients, answers)
product
# この解が正しければ、product配列の値は、dependentsのなかの値と非常に近くなっている

array([20., 13.])

In [16]:
# 二つの配列がほぼ等しいかどうかをチェックできる
# （浮動小数点の丸め誤差のため、ぴったりと一致しない場合もある）
np.allclose(product, dependents)
# (補足)Numpyには、多項式、フーリエ変換、統計、確率分布のためのモジュールもある

True