# 第11回勉強会

*Pandas*とは・・・高度なデータ構造を持ち、Pythonでデータ分析を素早く行うために設計された分析ツールを扱っている。

1. ラベル付けされたデータ構造を持ち、そのデータ構造では、自動的・明示的にデータを成形する機能がサポートされている。
1. 時系列データを扱う機能が統合されている。
1. 時系列データも非時系列データも同じデータ構造で扱うことができる。
1. 算術演算と集約演算にメタデータの情報を指定することができる。
1. 欠損値を柔軟に扱うことができる。
1. マージや一般的なSQLベースのデータベースで使用可能なその他の関係演算を扱うことができる。

## Pandasの読み込み方

In [7]:
import numpy as np
import pandas as pd

## Pandasのデータ構造

*Pandas*を始めるには*シリーズ(Series)*と*データフレーム(DataFrame)*という便利な2つのデータ構造に慣れる必要がある。

## Series

*Series*とは1次元配列のようなオブジェクトです。

In [4]:
# Series型の宣言
from pandas import Series
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [11]:
# Series型の値の取得
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [12]:
# Series型のインデックスの取得
obj.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
# インデックス付きのシリーズを作成する
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [15]:
# インデックスを指定して値の取得
obj2['a']

-5

In [16]:
# フィルタリング
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [18]:
# 掛け算
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [19]:
# データの存在確認
'b' in obj2

True

In [20]:
'e' in obj2

False

In [25]:
# ディクショナリをSeriesに変換
sdata = {'A': 35000, 'B': 71000, 'C': 16000, 'D': 5000}
sdata

{'A': 5000, 'B': 16000, 'C': 71000, 'D': 35000}

In [24]:
obj3 = Series(sdata)
obj3

A     5000
B    16000
C    71000
D    35000
dtype: int64

In [30]:
# データのマッピング
states = ['E', 'A', 'B', 'C']
obj4 = Series(sdata, index=states)
obj4

E        NaN
A     5000.0
B    16000.0
C    71000.0
dtype: float64

In [31]:
# nullチェック
pd.isnull(obj4)

E     True
A    False
B    False
C    False
dtype: bool

In [32]:
# not nulチェック
pd.notnull(obj4)

E    False
A     True
B     True
C     True
dtype: bool

In [33]:
# 算術演算
obj3 + obj4

A     10000.0
B     32000.0
C    142000.0
D         NaN
E         NaN
dtype: float64

## DataFrame

In [5]:
# DataFrameの宣言
from pandas import DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [39]:
# 列名を指定してDataFrameの作成
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [59]:
# 列と行を指定してDataFrameの宣言
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                  index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [60]:
# DataFrameの列を取得
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [61]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [62]:
# インデックス参照
frame2.ix['three']

C:\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\ipykernel\__main__.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  from ipykernel import kernelapp as app


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [63]:
# 列に一括で値を代入
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [64]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [65]:
# インデックスに対応するものが無い場合は欠損値が代入される
val = Series([-1.2, -1.5, -1.7], index=['two', 'three', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  -1.5
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.7

In [71]:
# 新し列の作成
frame2['eastern'] = frame2.state ==  'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6  -1.5     True
four   2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9  -1.7    False

In [72]:
# 列の削除
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  -1.5
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.7

In [73]:
# ディクショナリをDataFrameに変換
pop = {'Nevada': {2001: 2.4, 2002: 2.9,}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [74]:
# DataFrameの転置
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [76]:
# インデックスの指定
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [77]:
# DataFrameを2次元のndarrayに変換
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

## インデックスオブジェクト

In [82]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [83]:
# インデックスの変更はできない
index[1] = 'b'

TypeError: Index does not support mutable operations

In [88]:
# valuesの変更
value = obj.values
value

array([3, 1, 2])

In [87]:
value[0] = 3
value

array([3, 1, 2])

## Pandasの重要な機能

## 再インデックス付け

In [90]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [91]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [92]:
# 欠損値に代入
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [94]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [95]:
# 前方の値で穴埋め
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [96]:
# 後方の値で穴埋め
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

## 軸から要素を削除する

In [98]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [100]:
obj.drop(['c', 'b'])

a    0.0
d    3.0
e    4.0
dtype: float64

In [103]:
data = DataFrame(np.arange(16).reshape(4,4), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [106]:
# インデックス参照
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [107]:
obj['b']

1.0

In [108]:
obj[1]

1.0

In [111]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [113]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [115]:
# インデックスで指定した一部の値を変更
obj['b': 'd'] = 5
obj

a    0.0
b    5.0
c    5.0
d    5.0
dtype: float64

In [116]:
# 算術演算
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

In [117]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [118]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [119]:
# +演算子を使用すると軸ラベルが重複しないところはNA値になる
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [120]:
# add演算子の使用
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

## DataFrameとSeriesの演算

In [122]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [123]:
arr[0]

array([0., 1., 2., 3.])

In [124]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [127]:
# ブロードキャスト
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah','Ohip', 'taxas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohip    3.0   4.0   5.0
taxas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [129]:
series = frame.ix[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [130]:
# DataFrame - Series
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohip    3.0  3.0  3.0
taxas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [132]:
series2 = Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int32

In [133]:
# DataFrame + Series
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohip    3.0 NaN   6.0 NaN
taxas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [135]:
# DataFrame - Series
series3 = frame['d']
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohip   -1.0  0.0  1.0
taxas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 関数の適用

In [137]:
frame  = DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Taxas', 'oregon'])
frame

b         d         e
Utah   -0.202950  0.330043 -0.443764
Ohio   -0.459117 -1.442308 -0.754667
Taxas  -0.117942  1.420125  1.082489
oregon  0.907136  2.574436 -1.104481

In [138]:
np.abs(frame)

b         d         e
Utah    0.202950  0.330043  0.443764
Ohio    0.459117  1.442308  0.754667
Taxas   0.117942  1.420125  1.082489
oregon  0.907136  2.574436  1.104481

In [140]:
f = lambda x: x.max() - x. min()
frame.apply(f)

b    1.366253
d    4.016744
e    2.186969
dtype: float64

## ソート

In [144]:
# インデックスでのソート
obj = Series(range(4), index=['b', 'a', 'd', 'c'])
obj

b    0
a    1
d    2
c    3
dtype: int32

In [145]:
# ソート
obj.sort_index()

a    1
b    0
c    3
d    2
dtype: int32

In [146]:
obj.sort_index(ascending=False)

d    2
c    3
b    0
a    1
dtype: int32

In [153]:
# 値でのソート
obj1 = Series([4, 7, -3, 2])
obj1

0    4
1    7
2   -3
3    2
dtype: int64

In [154]:
obj1.order()

AttributeError: 'Series' object has no attribute 'order'

In [155]:
# 欠損地のソート
obj2 = Series([4, np.nan, 7, np.nan, -3, 2])
obj2

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [157]:
obj2.order()

AttributeError: 'Series' object has no attribute 'order'

## 要約統計量の集計と計算

*pandas*オブジェクトは、一般的な数学的、統計的なメソッドが使えます。これらのメソッドのほとんどが*集約*や*要約統計量*に分類されます

In [9]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two']) 
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [10]:
# 列の合計
df.sum()

one    9.25
two   -5.80
dtype: float64

In [13]:
# 行の合計
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [14]:
# skipnaオプションでNA値を計算対象から除外
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [16]:
# Max値のインデックスを取得
df.idxmax()

one    b
two    d
dtype: object

In [17]:
# 累積の値を取得
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [18]:
# 要約統計量
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

## 相関と共分散

In [26]:
# Yahooから株価と出来高のDataFrameを取得
import pandas.io.data as web
all_data = {}
for ticker in ['AAPL', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker, '1/1/2000', '1/1/2010')
    
price = DataFrame({tic: data['adj Close'] for tic, data in all_data.iteritems()})
volume = DataFrame({tic: data['volume'] for tic, data in all_data.iteritems()})

ImportError: The pandas.io.data module is moved to a separate package (pandas-datareader). After installing the pandas-datareader package (https://github.com/pydata/pandas-datareader), you can change the import ``from pandas.io import data, wb`` to ``from pandas_datareader import data, wb``.

In [27]:
# 株価のパーセント変化を求める
returns = price.pct_change()
returns.tail()

NameError: name 'price' is not defined

In [28]:
# 2つのSeriesのインデックス順に並んだ重なりから相関を求める
retuns.MSFT.corr(returns.IBM)

NameError: name 'retuns' is not defined

In [29]:
# covメソッドを共分散を求める
returns.MSFT.cov(returns.IBM)

NameError: name 'returns' is not defined

In [30]:
# corrwithメソッドは特定の行や列、別のSeriesやDataFrameとの相関を求められる
returns.corrwith(returns.IBM)

NameError: name 'returns' is not defined

In [31]:
returns.corrwith(volume)

NameError: name 'returns' is not defined

## 一意な値、頻度の確認、所属の確認

In [32]:
# 一意な値
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [33]:
# 頻度の確認
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [35]:
# 所属の確認
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

## 欠損値の取り扱い

In [36]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [38]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [39]:
# 欠損値を除外する
from numpy import nan as NA
data = Series([1, NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [40]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [41]:
# 欠損値を穴埋めする
data.fillna(0)

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

## 階層型インデックス

In [43]:
data = Series(np.random.randn(10), index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd', ], [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data

a  1   -2.113304
   2    2.042576
   3   -0.187837
b  1    1.396605
   2    0.478271
   3    0.933540
c  1   -0.441420
   2   -0.669728
d  2   -0.473624
   3   -0.791837
dtype: float64

In [45]:
# DataFrame型に構成
data.unstack()

1         2         3
a -2.113304  2.042576 -0.187837
b  1.396605  0.478271  0.933540
c -0.441420 -0.669728       NaN
d       NaN -0.473624 -0.791837